sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: z6zap7gDkZOMMSfneCAoGSsb5aHnpVaKmqR1xeZRDnbgWkLe54InrDLmuwuls7FER6EEsaKo2zjtNNrGL0uK+7dmKPpW4t7BPxCqSgA+OI9tjtbI+7gkihWL6iVN9agSvQM0Yai1hK0GE8U0A10ayz2ebIz+tJdzZZQKL1dN0wHVs+lgyf2uxSNANjyUprGn3RtiSTbyZ3E1/O07WHnFqBqdwZG7CBKklJ3YtiMBu13keMg3ZFYqkes10iWVQEHb6Ba4AZAQ4Udm5zcQE/PGtFeNHARYJn+AOgzlRpu6XJXpWJBcJKAR1bCg911aFTmYJPIlxhEq6pQ45loWO7/ybWhOCRBHKj9Fl6cbYuTL7TxFGIN1RxOdAiDpjPl4KUkZ+OEgICwMolirffcFaBZLSoRBeTTdY2UuO6VeAZPZEwl20HGrZJ24ptC/+UyiRzNyyuPU8hJCtM0y/MH89vaBn+qwHMD3MfloEdReBHYKoChH0oqQDfJ/FqT8Gu1FOfbvfJolZAQSG2xLKjtoe4DJzxaAS6djmgI+oN4VlWlvZD6Dp7KAYZx8a4TV0TCmdpS/KDMBZOFiqxp8iG8jt00vrUccuKFEPT8kdhk8m0ohst62FW0dQSEZTLbQV0/s2WcKlU8K1a+SkyHF3mlIRQBBul34gMZeXAks9Qdhe86hZ+k=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Flower-of-the-Mind_2080
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy